name: JMeter Test

on:
  push:
    branches:
      - main

jobs:
  jmeter:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JMeter test
        run: ./apache-jmeter-5.4.1/bin/jmeter -n -t C:\Program Files\apache-jmeter-5.5\bin\plans -l results.jtl
